# Generated by Django 4.1.1 on 2022-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('cm', models.FloatField()),
            ],
            options={
                'db_table': 'measure_measures',
            },
        ),
    ]
