# Generated by Django 4.1.1 on 2022-09-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0002_remove_measures_cm_remove_measures_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measures',
            name='cm',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measures',
            name='name',
            field=models.CharField(default='nn', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measures',
            name='reference',
            field=models.CharField(default='1234', max_length=30),
            preserve_default=False,
        ),
    ]
